//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyClickDoctorBE.App_Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyClickDoctorBE.App_Resources.AppResource", typeof(AppResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your change request was rejected. For more information please contact Myclickdoctor Helpdesk.
        /// </summary>
        public static string Admin_DenyStatus {
            get {
                return ResourceManager.GetString("Admin_DenyStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your change request was approved.
        /// </summary>
        public static string Admin_SuccessStatus {
            get {
                return ResourceManager.GetString("Admin_SuccessStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already exists.
        /// </summary>
        public static string alreadyExist {
            get {
                return ResourceManager.GetString("alreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your payment has already been refunded.
        /// </summary>
        public static string Alreadyrefund {
            get {
                return ResourceManager.GetString("Alreadyrefund", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment time.
        /// </summary>
        public static string ApointmentTime {
            get {
                return ResourceManager.GetString("ApointmentTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment details.
        /// </summary>
        public static string app_detail {
            get {
                return ResourceManager.GetString("app_detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The chosen time is already booked!.
        /// </summary>
        public static string appointment_booked {
            get {
                return ResourceManager.GetString("appointment_booked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment Confirmation.
        /// </summary>
        public static string appointment_confirmationsubject {
            get {
                return ResourceManager.GetString("appointment_confirmationsubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured. Please try again!.
        /// </summary>
        public static string appointment_failed {
            get {
                return ResourceManager.GetString("appointment_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment booked successfully.
        /// </summary>
        public static string appointment_success {
            get {
                return ResourceManager.GetString("appointment_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment title.
        /// </summary>
        public static string AppointmentTitle {
            get {
                return ResourceManager.GetString("AppointmentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment with.
        /// </summary>
        public static string Appointmentwith {
            get {
                return ResourceManager.GetString("Appointmentwith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banner Added Successfully.
        /// </summary>
        public static string Bannersucces {
            get {
                return ResourceManager.GetString("Bannersucces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your login details are the following:.
        /// </summary>
        public static string belowdetail {
            get {
                return ResourceManager.GetString("belowdetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best regards.
        /// </summary>
        public static string BestRegard {
            get {
                return ResourceManager.GetString("BestRegard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In case this button would not work, copy the following URL and open it in your browser:.
        /// </summary>
        public static string browserlink {
            get {
                return ResourceManager.GetString("browserlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear.
        /// </summary>
        public static string cahnge_dear {
            get {
                return ResourceManager.GetString("cahnge_dear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Myclickdoctor Helpdesk Team.
        /// </summary>
        public static string cahnge_team {
            get {
                return ResourceManager.GetString("cahnge_team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your following appointment has been cancelled:.
        /// </summary>
        public static string cancel_msg {
            get {
                return ResourceManager.GetString("cancel_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel meeting.
        /// </summary>
        public static string CancelMeeting {
            get {
                return ResourceManager.GetString("CancelMeeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sincerely yours.
        /// </summary>
        public static string change_sincyerly {
            get {
                return ResourceManager.GetString("change_sincyerly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been changed. In case you didn’t ask for it, please contact the Myclickdoctor Helpdesk..
        /// </summary>
        public static string changepass_msg {
            get {
                return ResourceManager.GetString("changepass_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click Here.
        /// </summary>
        public static string click_here {
            get {
                return ResourceManager.GetString("click_here", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please click on the link to login and generate your password.
        /// </summary>
        public static string clicklink {
            get {
                return ResourceManager.GetString("clicklink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I kindly ask you to contact the doctor regarding the registration..
        /// </summary>
        public static string contactdoctor {
            get {
                return ResourceManager.GetString("contactdoctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear.
        /// </summary>
        public static string Dear {
            get {
                return ResourceManager.GetString("Dear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear Myclickdoctor Helpdesk,.
        /// </summary>
        public static string dearteam {
            get {
                return ResourceManager.GetString("dearteam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctor.
        /// </summary>
        public static string Doctor {
            get {
                return ResourceManager.GetString("Doctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctor Category.
        /// </summary>
        public static string Doctor_Category {
            get {
                return ResourceManager.GetString("Doctor_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The consultation cannot be booked due to exceeded consultation limit.
        /// </summary>
        public static string DoctorConsultationRange {
            get {
                return ResourceManager.GetString("DoctorConsultationRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctor&apos;s name.
        /// </summary>
        public static string DoctorName {
            get {
                return ResourceManager.GetString("DoctorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You receive this e-mail because you missed a consultation booked to you. We would like to warn you that in case you miss a consultation booked to you again, you will be excluded from Myclickdoctor. In case you can&apos;t attend to an appointment you can cancel it: more than 12 hours before the consultation you can do it yourself, while within 12 hours please contact Myclickdoctor Helpdesk in order to do so. Please note that this is an automatically generated e-mail, if you need help, please contact Myclickdoctor [rest of string was truncated]&quot;;.
        /// </summary>
        public static string doctorwarningmsg {
            get {
                return ResourceManager.GetString("doctorwarningmsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        public static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here is the confirmation code for your Verification.
        /// </summary>
        public static string EmailAuthMsg {
            get {
                return ResourceManager.GetString("EmailAuthMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An e-mail has been sent to your address with instructions on how to reset your password.
        /// </summary>
        public static string emailverify {
            get {
                return ResourceManager.GetString("emailverify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please click on the following link to reset your password.
        /// </summary>
        public static string forget_Link_Reset {
            get {
                return ResourceManager.GetString("forget_Link_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You asked to restore your password. To create a new password, please, click on the button below:.
        /// </summary>
        public static string forgetblow {
            get {
                return ResourceManager.GetString("forgetblow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In case you didn’t ask to restore your password, you don’t have anything to do, simply disregard this e-mail..
        /// </summary>
        public static string forgetDiscard {
            get {
                return ResourceManager.GetString("forgetDiscard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password.
        /// </summary>
        public static string ForgetPassword {
            get {
                return ResourceManager.GetString("ForgetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We received a request that you want to restore the password.
        /// </summary>
        public static string forgetRecive_request {
            get {
                return ResourceManager.GetString("forgetRecive_request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nice.
        /// </summary>
        public static string Hi {
            get {
                return ResourceManager.GetString("Hi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear.
        /// </summary>
        public static string HiThere {
            get {
                return ResourceManager.GetString("HiThere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model is invalid!.
        /// </summary>
        public static string invalid_model {
            get {
                return ResourceManager.GetString("invalid_model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username or password.
        /// </summary>
        public static string invalid_username {
            get {
                return ResourceManager.GetString("invalid_username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invitation.
        /// </summary>
        public static string Invitation {
            get {
                return ResourceManager.GetString("Invitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I kindly ask you to contact the following doctor in order to register him/her to Myclickdoctor..
        /// </summary>
        public static string invitekind {
            get {
                return ResourceManager.GetString("invitekind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I would like to invite a new doctor to Myclickdoctor. His/her details are the following:.
        /// </summary>
        public static string invitemsg {
            get {
                return ResourceManager.GetString("invitemsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice uploaded successfully!.
        /// </summary>
        public static string invoice_upload {
            get {
                return ResourceManager.GetString("invoice_upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kindly contact us in any case of issue.
        /// </summary>
        public static string KindlyContact {
            get {
                return ResourceManager.GetString("KindlyContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logged in.
        /// </summary>
        public static string login_success {
            get {
                return ResourceManager.GetString("login_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The e-mail you entered is invalid, please check again.
        /// </summary>
        public static string Mail_invalid {
            get {
                return ResourceManager.GetString("Mail_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Can&apos;t Book because Time Slot limit is Over!.
        /// </summary>
        public static string MaxAccesseedCallCount {
            get {
                return ResourceManager.GetString("MaxAccesseedCallCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Myclickdoctor Helpdesk has made changes in certain informations on your account..
        /// </summary>
        public static string MCDchange {
            get {
                return ResourceManager.GetString("MCDchange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your registration to Myclickdoctor was successful!.
        /// </summary>
        public static string medicalregister {
            get {
                return ResourceManager.GetString("medicalregister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Morbidity.
        /// </summary>
        public static string Morbidity {
            get {
                return ResourceManager.GetString("Morbidity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please click on the below button to view your Morbidity.
        /// </summary>
        public static string Morbiditymsg {
            get {
                return ResourceManager.GetString("Morbiditymsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To book a new appointment, please enter Myclickdoctor..
        /// </summary>
        public static string newAppointment {
            get {
                return ResourceManager.GetString("newAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no available nurses for the chosen time.
        /// </summary>
        public static string no_nurse {
            get {
                return ResourceManager.GetString("no_nurse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No refund.
        /// </summary>
        public static string NotRefund {
            get {
                return ResourceManager.GetString("NotRefund", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nurse.
        /// </summary>
        public static string Nurse {
            get {
                return ResourceManager.GetString("Nurse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old password is incorrect.
        /// </summary>
        public static string Old_Password {
            get {
                return ResourceManager.GetString("Old_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partial appointment only book for patient.
        /// </summary>
        public static string partial_appointment {
            get {
                return ResourceManager.GetString("partial_appointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient.
        /// </summary>
        public static string Patient {
            get {
                return ResourceManager.GetString("Patient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successful registration! We sent you an e-mail with the instructions to set up your password. Please check your inbox.
        ///Warning! If you don&apos;t activate your profile within 24 hours, your registration will be lost! (You can register again anytime later.).
        /// </summary>
        public static string PatientSuccess {
            get {
                return ResourceManager.GetString("PatientSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have  already booked this time slot for another appointment..
        /// </summary>
        public static string pharma_slot {
            get {
                return ResourceManager.GetString("pharma_slot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pharmaceutical company.
        /// </summary>
        public static string PharmaceuticalCompany {
            get {
                return ResourceManager.GetString("PharmaceuticalCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pharma representative.
        /// </summary>
        public static string PharmaRepresentative {
            get {
                return ResourceManager.GetString("PharmaRepresentative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Profile detail changed by the Admin.Please contact with Helpdesk Team.
        /// </summary>
        public static string Profilechanged {
            get {
                return ResourceManager.GetString("Profilechanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile confirmation.
        /// </summary>
        public static string ProfileConfirmation {
            get {
                return ResourceManager.GetString("ProfileConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your profile change request was accepted by Myclickdoctor Helpdesk..
        /// </summary>
        public static string ProfileRequest {
            get {
                return ResourceManager.GetString("ProfileRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your profile change request was rejected.
        /// </summary>
        public static string ProfileRequestDeny {
            get {
                return ResourceManager.GetString("ProfileRequestDeny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your payment refund request is being processed.
        /// </summary>
        public static string refindsuccessmsg {
            get {
                return ResourceManager.GetString("refindsuccessmsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refund.
        /// </summary>
        public static string Refund_status {
            get {
                return ResourceManager.GetString("Refund_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration confirmation.
        /// </summary>
        public static string RegistrationConfirmation {
            get {
                return ResourceManager.GetString("RegistrationConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A mail successfully sent to Myclickdoctor Helpdesk.
        /// </summary>
        public static string sendmailAdmin {
            get {
                return ResourceManager.GetString("sendmailAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Morbidity share successfully.
        /// </summary>
        public static string sharesuccess {
            get {
                return ResourceManager.GetString("sharesuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A time slot is already added for this duration.
        /// </summary>
        public static string Slot_added {
            get {
                return ResourceManager.GetString("Slot_added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are very sorry for any inconvenience caused..
        /// </summary>
        public static string sorry {
            get {
                return ResourceManager.GetString("sorry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specialty.
        /// </summary>
        public static string Speciality {
            get {
                return ResourceManager.GetString("Speciality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment&apos;s start.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account information has been changed.
        /// </summary>
        public static string subject_changed {
            get {
                return ResourceManager.GetString("subject_changed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An appointment was booked to you in Myclickdoctor. The details of the appointment are the following:.
        /// </summary>
        public static string success_appointment {
            get {
                return ResourceManager.GetString("success_appointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully Saved.
        /// </summary>
        public static string SuccessfullySaved {
            get {
                return ResourceManager.GetString("SuccessfullySaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you very much.
        /// </summary>
        public static string Thanks {
            get {
                return ResourceManager.GetString("Thanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctor Time Slot Creation.
        /// </summary>
        public static string TimeslotcreationemailSubject {
            get {
                return ResourceManager.GetString("TimeslotcreationemailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the TimeSlot Details.
        /// </summary>
        public static string Timeslotmsg {
            get {
                return ResourceManager.GetString("Timeslotmsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TimeZone.
        /// </summary>
        public static string TimeZone {
            get {
                return ResourceManager.GetString("TimeZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topic.
        /// </summary>
        public static string Topic {
            get {
                return ResourceManager.GetString("Topic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Can&apos;t Book because Time  is Over!.
        /// </summary>
        public static string twohourbefore {
            get {
                return ResourceManager.GetString("twohourbefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added successfully.
        /// </summary>
        public static string user_Added {
            get {
                return ResourceManager.GetString("user_Added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes are on approval.
        /// </summary>
        public static string user_approve {
            get {
                return ResourceManager.GetString("user_approve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account was approved successfully!.
        /// </summary>
        public static string user_Approved {
            get {
                return ResourceManager.GetString("user_Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned successfully.
        /// </summary>
        public static string user_assign {
            get {
                return ResourceManager.GetString("user_assign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account was blocked by Myclickdoctor Helpdesk. Please contact them for further information!.
        /// </summary>
        public static string user_Blocked {
            get {
                return ResourceManager.GetString("user_Blocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your appointment was canceled.
        /// </summary>
        public static string user_cancel {
            get {
                return ResourceManager.GetString("user_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted successfully.
        /// </summary>
        public static string user_delete {
            get {
                return ResourceManager.GetString("user_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document successfully added!.
        /// </summary>
        public static string user_docsuccess {
            get {
                return ResourceManager.GetString("user_docsuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This e-mail already exists!.
        /// </summary>
        public static string user_exist {
            get {
                return ResourceManager.GetString("user_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured. Please try again!.
        /// </summary>
        public static string user_Failed {
            get {
                return ResourceManager.GetString("user_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your feedback was submitted successfully.
        /// </summary>
        public static string user_feedback {
            get {
                return ResourceManager.GetString("user_feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We have sent you an e-mail with instructions on how to reset your password. If you don&apos;t receive anything from us, please check your Spambox. In case it&apos;s not there, contact Myclickdoctor Helpdesk..
        /// </summary>
        public static string user_forget {
            get {
                return ResourceManager.GetString("user_forget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No file selected.
        /// </summary>
        public static string user_Img {
            get {
                return ResourceManager.GetString("user_Img", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There&apos;s no data.
        /// </summary>
        public static string user_listE {
            get {
                return ResourceManager.GetString("user_listE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data found.
        /// </summary>
        public static string user_listS {
            get {
                return ResourceManager.GetString("user_listS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request sent successfully.
        /// </summary>
        public static string user_notify {
            get {
                return ResourceManager.GetString("user_notify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password updated successfully.
        /// </summary>
        public static string user_password {
            get {
                return ResourceManager.GetString("user_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account is waiting for approval. You can login only once your account has been approved..
        /// </summary>
        public static string user_Pending {
            get {
                return ResourceManager.GetString("user_Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The changes were rejected.
        /// </summary>
        public static string user_reject {
            get {
                return ResourceManager.GetString("user_reject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request sent successfully.
        /// </summary>
        public static string user_request {
            get {
                return ResourceManager.GetString("user_request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctor already booked this time slot for another appointment..
        /// </summary>
        public static string user_slot {
            get {
                return ResourceManager.GetString("user_slot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration successful.
        /// </summary>
        public static string user_Success {
            get {
                return ResourceManager.GetString("user_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile updated successfully.
        /// </summary>
        public static string user_SuccessUpdate {
            get {
                return ResourceManager.GetString("user_SuccessUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated successfully.
        /// </summary>
        public static string user_update {
            get {
                return ResourceManager.GetString("user_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification.
        /// </summary>
        public static string Verification {
            get {
                return ResourceManager.GetString("Verification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string warning {
            get {
                return ResourceManager.GetString("warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to select a time slot lasting at least 20 minutes..
        /// </summary>
        public static string wrong_slot {
            get {
                return ResourceManager.GetString("wrong_slot", resourceCulture);
            }
        }
    }
}
